-- Access rules of wishlists, wishes, reservations and visited lists.
-- Léa owns a list; Hugo and Camille are relatives who have its link.
begin;
select plan(39);

insert into auth.users (id, email) values
  ('11111111-1111-1111-1111-111111111111', 'lea@example.test'),
  ('22222222-2222-2222-2222-222222222222', 'hugo@example.test'),
  ('33333333-3333-3333-3333-333333333333', 'camille@example.test');
update public.profiles set display_name = 'Léa' where id = '11111111-1111-1111-1111-111111111111';
update public.profiles set display_name = 'Hugo' where id = '22222222-2222-2222-2222-222222222222';
update public.profiles set display_name = 'Camille' where id = '33333333-3333-3333-3333-333333333333';

-- Fixtures, written with full rights: fixed ids keep the checks below readable.
insert into public.wishlists (id, owner_id, name) values
  ('aaaaaaaa-0000-0000-0000-000000000001', '11111111-1111-1111-1111-111111111111', 'Noël 2026');
insert into public.wishes (id, wishlist_id, name, price_cents, url) values
  ('bbbbbbbb-0000-0000-0000-000000000001', 'aaaaaaaa-0000-0000-0000-000000000001', 'Casque', 34900, 'https://example.com/casque'),
  ('bbbbbbbb-0000-0000-0000-000000000002', 'aaaaaaaa-0000-0000-0000-000000000001', 'Plaid', null, null);
update public.wishes set created_at = created_at - interval '1 minute'
  where id = 'bbbbbbbb-0000-0000-0000-000000000001';

-- As Léa, the owner
set local role authenticated;
set local request.jwt.claims = '{"sub": "11111111-1111-1111-1111-111111111111", "role": "authenticated"}';

select lives_ok(
  $$ insert into public.wishlists (name) values ('Anniversaire') $$,
  'A user can create a list'
);

select is(
  (select owner_id from public.wishlists where name = 'Anniversaire'),
  '11111111-1111-1111-1111-111111111111'::uuid,
  'A new list belongs to its creator'
);

select throws_ok(
  $$ insert into public.wishlists (id, name) values (gen_random_uuid(), 'Choisie') $$,
  '42501',
  null,
  'Ids are always generated by the database'
);

select throws_ok(
  $$ insert into public.wishlists (name, owner_id) values ('Volée', '22222222-2222-2222-2222-222222222222') $$,
  '42501',
  null,
  'Nobody can create a list on behalf of someone else'
);

select throws_ok(
  $$ insert into public.wishlists (name) values ('   ') $$,
  '23514',
  null,
  'A list name cannot be blank'
);

select throws_ok(
  $$ insert into public.wishlists (name) values (repeat('a', 51)) $$,
  '23514',
  null,
  'A list name is 50 characters at most'
);

select lives_ok(
  $$ update public.wishlists set name = 'Noël en famille' where id = 'aaaaaaaa-0000-0000-0000-000000000001' $$,
  'The owner can rename their list'
);

select lives_ok(
  $$ insert into public.wishes (wishlist_id, name, price_cents) values
       ((select id from public.wishlists where name = 'Anniversaire'), 'Vinyle', 2500) $$,
  'The owner can add wishes to their list'
);

select is(
  (select currency from public.wishes where name = 'Vinyle'),
  'EUR',
  'Prices are in euros unless said otherwise'
);

select lives_ok(
  $$ delete from public.wishlists where name = 'Anniversaire' $$,
  'The owner can delete their list'
);

select throws_ok(
  $$ insert into public.wishes (wishlist_id, name, url) values ('aaaaaaaa-0000-0000-0000-000000000001', 'Piège', 'javascript:alert(1)') $$,
  '23514',
  null,
  'A wish link can only be a web address'
);

select throws_ok(
  $$ insert into public.wishes (wishlist_id, name, price_cents) values ('aaaaaaaa-0000-0000-0000-000000000001', 'Remboursé', -100) $$,
  '23514',
  null,
  'A price cannot be negative'
);

select throws_ok(
  $$ insert into public.wishes (wishlist_id, name, currency) values ('aaaaaaaa-0000-0000-0000-000000000001', 'Exotique', 'euro') $$,
  '23514',
  null,
  'A currency is an ISO 4217 code'
);

select throws_ok(
  $$ insert into public.reservations (wish_id) values ('bbbbbbbb-0000-0000-0000-000000000001') $$,
  '42501',
  null,
  'An owner cannot reserve a wish of their own list'
);

-- As Hugo, a relative
set local request.jwt.claims = '{"sub": "22222222-2222-2222-2222-222222222222", "role": "authenticated"}';

select is_empty(
  'select id from public.wishlists',
  'Lists cannot be enumerated by anyone but their owner'
);

select is_empty(
  'select id from public.wishes',
  'Wishes cannot be read directly by anyone but the owner'
);

select throws_ok(
  $$ insert into public.wishes (wishlist_id, name) values ('aaaaaaaa-0000-0000-0000-000000000001', 'Intrus') $$,
  '42501',
  null,
  'Nobody can add a wish to someone else''s list'
);

update public.wishlists set name = 'Piratée' where id = 'aaaaaaaa-0000-0000-0000-000000000001';
update public.wishes set name = 'Piraté' where id = 'bbbbbbbb-0000-0000-0000-000000000001';
delete from public.wishes where id = 'bbbbbbbb-0000-0000-0000-000000000002';
delete from public.wishlists where id = 'aaaaaaaa-0000-0000-0000-000000000001';

select lives_ok(
  $$ insert into public.reservations (wish_id) values ('bbbbbbbb-0000-0000-0000-000000000001') $$,
  'A relative can reserve a wish'
);

select throws_ok(
  $$ insert into public.reservations (wish_id) values ('bbbbbbbb-0000-0000-0000-000000000001') $$,
  '23505',
  null,
  'A relative cannot reserve the same wish twice'
);

select throws_ok(
  $$ insert into public.reservations (wish_id, user_id) values ('bbbbbbbb-0000-0000-0000-000000000002', '33333333-3333-3333-3333-333333333333') $$,
  '42501',
  null,
  'Nobody can reserve on behalf of someone else'
);

select is(
  public.wishlist_view('aaaaaaaa-0000-0000-0000-000000000001') -> 'wishes' -> 1 -> 'reservations',
  '[{"name": "Hugo", "is_me": true}]'::jsonb,
  'A relative sees their own reservation'
);

select is(
  (select array_agg(wishlist_id) from public.visited_wishlists()),
  array['aaaaaaaa-0000-0000-0000-000000000001'::uuid],
  'Opening a list adds it to the relative''s visited lists'
);

-- As Camille, another relative
set local request.jwt.claims = '{"sub": "33333333-3333-3333-3333-333333333333", "role": "authenticated"}';

select is_empty(
  'select * from public.reservations',
  'Reservations of others cannot be read directly'
);

select lives_ok(
  $$ insert into public.reservations (wish_id) values ('bbbbbbbb-0000-0000-0000-000000000001') $$,
  'Several relatives can go in on the same wish'
);

select is(
  public.wishlist_view('aaaaaaaa-0000-0000-0000-000000000001') -> 'wishes' -> 1 -> 'reservations',
  '[{"name": "Hugo", "is_me": false}, {"name": "Camille", "is_me": true}]'::jsonb,
  'Relatives see who else is on a wish'
);

delete from public.reservations where wish_id = 'bbbbbbbb-0000-0000-0000-000000000001'
  and user_id = '22222222-2222-2222-2222-222222222222';

select is(
  jsonb_array_length(public.wishlist_view('aaaaaaaa-0000-0000-0000-000000000001') -> 'wishes' -> 1 -> 'reservations'),
  2,
  'Nobody can cancel someone else''s reservation'
);

select lives_ok(
  $$ delete from public.reservations where wish_id = 'bbbbbbbb-0000-0000-0000-000000000001' $$,
  'A relative can cancel their reservation'
);

select is(
  public.wishlist_view('aaaaaaaa-0000-0000-0000-000000000001') -> 'wishes' -> 1 -> 'reservations',
  '[{"name": "Hugo", "is_me": false}]'::jsonb,
  'Cancelling only removes the caller''s own reservation'
);

-- Back as Léa, the owner: the surprise is kept
set local request.jwt.claims = '{"sub": "11111111-1111-1111-1111-111111111111", "role": "authenticated"}';

select is(
  (select name from public.wishlists where id = 'aaaaaaaa-0000-0000-0000-000000000001'),
  'Noël en famille',
  'Relatives cannot rename, empty or delete someone else''s list'
);

select is_empty(
  'select * from public.reservations',
  'The owner cannot read the reservations of their list'
);

select is_empty(
  $$ select 1 from jsonb_array_elements(public.wishlist_view('aaaaaaaa-0000-0000-0000-000000000001') -> 'wishes') w
     where w ? 'reservations' $$,
  'The owner''s view of their list has no reservations at all'
);

select is(
  public.wishlist_view('aaaaaaaa-0000-0000-0000-000000000001') ->> 'owner_name',
  'Léa',
  'A list shows its owner''s name'
);

select is_empty(
  'select * from public.visited_wishlists()',
  'Opening one''s own list is not a visit'
);

select is(
  public.wishlist_view('aaaaaaaa-0000-0000-0000-00000000dead'),
  null,
  'An unknown list is null, whoever asks'
);

-- Anonymous visitors, with the link
set local role anon;
reset request.jwt.claims;

select is(
  jsonb_array_length(public.wishlist_view('aaaaaaaa-0000-0000-0000-000000000001') -> 'wishes'),
  2,
  'Anyone with the link can see the wishes'
);

select is_empty(
  $$ select 1 from jsonb_array_elements(public.wishlist_view('aaaaaaaa-0000-0000-0000-000000000001') -> 'wishes') w
     where w ? 'reservations' $$,
  'Anonymous visitors never see reservations, so the owner cannot just sign out to look'
);

select throws_ok(
  'select * from public.wishlists',
  '42501',
  null,
  'Anonymous visitors cannot read the tables'
);

select throws_ok(
  'select * from public.visited_wishlists()',
  '42501',
  null,
  'Anonymous visitors have no visited lists'
);

-- Deleting a list takes its wishes, reservations and visits with it
set local role authenticated;
set local request.jwt.claims = '{"sub": "11111111-1111-1111-1111-111111111111", "role": "authenticated"}';
delete from public.wishlists where id = 'aaaaaaaa-0000-0000-0000-000000000001';
reset role;

select is(
  (select count(*)::int from public.wishes) + (select count(*)::int from public.reservations)
    + (select count(*)::int from public.wishlist_visits),
  0,
  'Deleting a list deletes everything attached to it'
);

select * from finish();
rollback;
