services:
  frontend:
    image: rakl/wishlist-client:latest
    ports:
      - 8000:80
    depends_on:
      - backend
  
  backend:
    image: rakl/wishlist-server:latest
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_HTTP_PORT=7200
      - ASPNETCORE_HTTPS_PORT=7201