services:

  postgres:
    container_name: wishlist-database
    image: postgres:latest
    environment:
      POSTGRES_DB: wishlist
      POSTGRES_USER: wishlist
      POSTGRES_PASSWORD: abcd
    ports:
      - 5432:5432
    volumes:
      - wishlist-database:/var/lib/postgresql/data

  backend:
    container_name: wishlist-server
    image: rakl/wishlist-server:latest
    ports:
      - 7200:7200
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:7200
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=wishlist;User ID=wishlist;Password=abcd;Port=5432
      - Network__ClientUrl=https://wishlist.raki.app
      - Email__SmtpServer=
      - Email__SmtpPort=
      - Email__SmtpUsername=
      - Email__SmtpPassword=
    volumes:
      - /etc/letsencrypt:/app/https
    depends_on:
      - postgres

  frontend:
    container_name: wishlist-client
    image: rakl/wishlist-client:latest
    ports:
      - 8000:80
    depends_on:
      - backend

volumes:
    wishlist-database: