services:

  postgres:
    container_name: wishlist-database
    image: postgres:latest
    environment:
      POSTGRES_DB: wishlist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - wishlist-database:/var/lib/postgresql/data

  backend:
    container_name: wishlist-server
    image: rakl/wishlist-server:latest
    ports:
      - 7200:7200
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:7200
    volumes:
      - /etc/letsencrypt:/https
    links:
      - postgres

  frontend:
    container_name: wishlist-client
    image: rakl/wishlist-client:latest
    ports:
      - 8000:80
    links:
      - backend

volumes:
    wishlist-database: