services:
  frontend:
    container_name: wishlist-client
    image: rakl/wishlist-client:latest
    ports:
      - 8000:80
    depends_on:
      - backend
  
  backend:
    container_name: wishlist-server
    image: rakl/wishlist-server:latest
    ports:
      - 7200:80
    environment:
      - ASPNETCORE_HTTP_PORT=7200
      - ASPNETCORE_HTTPS_PORT=7201