name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image for server
      uses: docker/build-push-action@v5
      with:
        context: ./Server
        file: ./Server/Dockerfile
        push: true
        tags: rakl/wishlist-server:latest

  build-client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image for client
      uses: docker/build-push-action@v5
      with:
        context: ./Client
        file: ./Client/Dockerfile
        push: true
        tags: rakl/wishlist-client:latest
